export const CODIGOS_EXPEDIENTES = [
  { codigo: "GENE00001", descripcion: "Promoción Industrial" },
  { codigo: "GENE00002", descripcion: "Promoción Industrial, Parques Industriales" },
  { codigo: "GENE00003", descripcion: "Radicación de Industria" },
  { codigo: "GENE00004", descripcion: "Proyecto de Decreto" },
  { codigo: "GENE00005", descripcion: "Proyecto de Disposición" },
  { codigo: "GENE00006", descripcion: "Proyecto de Ley" },
  { codigo: "GENE00007", descripcion: "Proyecto de Resolución" },
  { codigo: "GENE00008", descripcion: "Estudio de Impacto Ambiental" },
  { codigo: "GENE00009", descripcion: "Autorizaciones en General" },
  { codigo: "GENE00010", descripcion: "Certificaciones en General" },
  { codigo: "GENE00011", descripcion: "Renovación De Certificado De Aptitud Ambiental" },
  { codigo: "GENE00012", descripcion: "Solicitud De Certificado" },
  { codigo: "GENE00013", descripcion: "Certificado De Deuda" },
  { codigo: "GENE00014", descripcion: "Cobro De Deuda" },
  { codigo: "GENE00015", descripcion: "Condonación De Deuda" },
  { codigo: "GENE00016", descripcion: "Cumplimiento Tributario" },
  { codigo: "GENE00017", descripcion: "Eximiciones Y Exenciones" },
  { codigo: "GENE00018", descripcion: "Patentes De Vehículos" },
  { codigo: "GENE00019", descripcion: "Reconocimiento De Deuda" },
  { codigo: "GENE00020", descripcion: "Tributos En General - Moratorias" },
  { codigo: "GENE00021", descripcion: "Unificación De Partidas" },
  { codigo: "GENE00022", descripcion: "Compra Directa" },
  { codigo: "GENE00023", descripcion: "Concesiones" },
  { codigo: "GENE00024", descripcion: "Contratación Directa" },
  { codigo: "GENE00025", descripcion: "Licitación Privada" },
  { codigo: "GENE00026", descripcion: "Licitación Pública" },
  { codigo: "GENE00027", descripcion: "Licitación/Contratación Penalidades" },
  { codigo: "GENE00028", descripcion: "Contaduría Y Tesorería" },
  { codigo: "GENE00029", descripcion: "Adhesiones" },
  { codigo: "GENE00030", descripcion: "Contratos, Locación De Obra" },
  { codigo: "GENE00031", descripcion: "Contratos, Locación De Servicios" },
  { codigo: "GENE00032", descripcion: "Convenios" },
  { codigo: "GENE00033", descripcion: "Ejecución Convenio" },
  { codigo: "GENE00034", descripcion: "Declaraciones" },
  { codigo: "GENE00035", descripcion: "Denuncia, Defensa Del Consumidor, Lealtad Comercial" },
  { codigo: "GENE00036", descripcion: "Denuncias" },
  { codigo: "GENE00037", descripcion: "Mediación" },
  { codigo: "GENE00038", descripcion: "Siniestro" },
  { codigo: "GENE00039", descripcion: "Donaciones" },
  { codigo: "GENE00040", descripcion: "Donaciones De Inmueble" },
  { codigo: "GENE00041", descripcion: "Entidades" },
  { codigo: "GENE00042", descripcion: "Categorización De Industrias" },
  { codigo: "GENE00043", descripcion: "Fiscalización" },
  { codigo: "GENE00044", descripcion: "Fiscalización, Seguridad E Higiene" },
  { codigo: "GENE00045", descripcion: "Inscripciones" },
  { codigo: "GENE00046", descripcion: "Investigación Presumarial" },
  { codigo: "GENE00047", descripcion: "Prefactibilidad" },
  { codigo: "GENE00048", descripcion: "Reintegros En General" },
  { codigo: "GENE00049", descripcion: "Frente Marítimo" },
  { codigo: "GENE00050", descripcion: "Baja De Comercios" },
  { codigo: "GENE00051", descripcion: "Baja De Depósito" },
  { codigo: "GENE00052", descripcion: "Baja De Industrias" },
  { codigo: "GENE00053", descripcion: "Baja De Vehículos" },
  { codigo: "GENE00054", descripcion: "Habilitaciones Ampliación De Rubro Y/O Superficie" },
  { codigo: "GENE00055", descripcion: "Habilitaciones Antenas" },
  { codigo: "GENE00056", descripcion: "Habilitaciones Carteles" },
  { codigo: "GENE00057", descripcion: "Habilitaciones Comercios" },
  { codigo: "GENE00058", descripcion: "Habilitaciones De Microemprendimientos" },
  { codigo: "GENE00059", descripcion: "Habilitaciones De Vehículos" },
  { codigo: "GENE00060", descripcion: "Habilitaciones Depósito" },
  { codigo: "GENE00061", descripcion: "Habilitaciones Industrias" },
  { codigo: "GENE00062", descripcion: "Transferencias De Industrias" },
  { codigo: "GENE00063", descripcion: "Transferencias De Bóvedas" },
  { codigo: "GENE00064", descripcion: "Transferencias De Comercios" },
  { codigo: "GENE00065", descripcion: "Traslados De Comercios" },
  { codigo: "GENE00066", descripcion: "Historia Clínica" },
  { codigo: "GENE00067", descripcion: "Alquileres" },
  { codigo: "GENE00068", descripcion: "Compra De Inmueble" },
  { codigo: "GENE00069", descripcion: "Predios En General" },
  { codigo: "GENE00070", descripcion: "Predios Fiscales" },
  { codigo: "GENE00071", descripcion: "Registración De Plano" },
  { codigo: "GENE00072", descripcion: "Regularización Dominial" },
  { codigo: "GENE00073", descripcion: "Uso Conforme De Suelo" },
  { codigo: "GENE00074", descripcion: "Visación De Plano De Mensura" },
  { codigo: "GENE00075", descripcion: "Licencia Conductor" },
  { codigo: "GENE00076", descripcion: "Licencias De Conducir" },
  { codigo: "GENE00077", descripcion: "Aprobación De Plano" },
  { codigo: "GENE00078", descripcion: "Aviso De Obra/Autorización De Obra" },
  { codigo: "GENE00079", descripcion: "Certificado De Zonificación" },
  { codigo: "GENE00080", descripcion: "Copia De Plano" },
  { codigo: "GENE00081", descripcion: "Final De Obra" },
  { codigo: "GENE00082", descripcion: "Contratación Directa De Obra" },
  { codigo: "GENE00083", descripcion: "Ejecución De Obra" },
  { codigo: "GENE00084", descripcion: "Ejecución Licitación/Contratación" },
  { codigo: "GENE00085", descripcion: "Licitación Privada De Obra" },
  { codigo: "GENE00086", descripcion: "Licitación Pública De Obra" },
  { codigo: "GENE00087", descripcion: "Oficio Judicial" },
  { codigo: "GENE00088", descripcion: "Oficio Judicial Reservado" },
  { codigo: "GENE00089", descripcion: "Pago De Deudas" },
  { codigo: "GENE00090", descripcion: "Pagos Y Acreditaciones" },
  { codigo: "GENE00091", descripcion: "Permiso" },
  { codigo: "GENE00092", descripcion: "Ajuste De Presupuesto" },
  { codigo: "GENE00093", descripcion: "Presupuesto" },
  { codigo: "GENE00094", descripcion: "Programa Elementos Ortopédicos" },
  { codigo: "GENE00095", descripcion: "Programas" },
  { codigo: "GENE00096", descripcion: "Reclamos" },
  { codigo: "GENE00097", descripcion: "Contratación De Agente" },
  { codigo: "GENE00098", descripcion: "Designación Docente" },
  { codigo: "GENE00099", descripcion: "Disponibilidad De Agente" },
  { codigo: "GENE00100", descripcion: "Indemnizaciones" },
  { codigo: "GENE00101", descripcion: "Jubilaciones Y Pensiones" },
  { codigo: "GENE00102", descripcion: "Licencia Por Maternidad" },
  { codigo: "GENE00103", descripcion: "Licencia Por Matrimonio" },
  { codigo: "GENE00104", descripcion: "Planilla De Guardias" },
  { codigo: "GENE00105", descripcion: "Recupero De Honorarios" },
  { codigo: "GENE00106", descripcion: "Recursos Humanos Baja De Agente" },
  { codigo: "GENE00107", descripcion: "Recursos Humanos Designación De Agente" },
  { codigo: "GENE00108", descripcion: "Recursos Humanos Designación De Funcionario, Autoridad Superior" },
  { codigo: "GENE00109", descripcion: "Recursos Humanos Licencias Especiales" },
  { codigo: "GENE00110", descripcion: "Renuncias" },
  { codigo: "GENE00111", descripcion: "Certificado De Discapacidad" },
  { codigo: "GENE00112", descripcion: "Inscripción Registro De Entidades" },
  { codigo: "GENE00113", descripcion: "Inscripción Registro De Productos" },
  { codigo: "GENE00114", descripcion: "Inscripción Registro De Profesionales" },
  { codigo: "GENE00115", descripcion: "Registro/Inscripción De Profesionales" },
  { codigo: "GENE00116", descripcion: "Registro/Inscripción De Productos" },
  { codigo: "GENE00117", descripcion: "Registro/Inscripción De Proveedor" },
  { codigo: "GENE00118", descripcion: "Reglamentaciones En General" },
  { codigo: "GENE00119", descripcion: "Reserva De Sala / Salones Y Otros" },
  { codigo: "GENE00120", descripcion: "Salud - Medicamentos" },
  { codigo: "GENE00121", descripcion: "Habilitación Sistema Anterior" },
  { codigo: "GENE00122", descripcion: "Solicitud De Cambio De Categoría" },
  { codigo: "GENE00123", descripcion: "Solicitud De Constancia De Parto" },
  { codigo: "GENE00124", descripcion: "Solicitud De Desarchivo" },
  { codigo: "GENE00125", descripcion: "Solicitud De Informe" },
  { codigo: "GENE00126", descripcion: "Subsidios" },
  { codigo: "GENE00127", descripcion: "Sumarios" },
  { codigo: "GENE00128", descripcion: "Transferencias En General" },
  { codigo: "GENE00129", descripcion: "Agua Corriente-Cloacas" },
  { codigo: "GENE00130", descripcion: "Espectáculos Públicos" },
  { codigo: "GENE00131", descripcion: "Gas Natural-Redes De Gas" },
  { codigo: "GENE00132", descripcion: "Pavimentación" },
  { codigo: "GENE00133", descripcion: "Vía Pública-Permiso De Apertura" },
  { codigo: "GENE00134", descripcion: "Vía Pública-Permiso De Uso" },
  { codigo: "GENE00135", descripcion: "Violencia Familiar" },
  { codigo: "GENE00136", descripcion: "Bien De Familia" },
  { codigo: "GENE00137", descripcion: "Escrituraciones" },
  { codigo: "GENE00138", descripcion: "Tierras Y Vivienda" },
  { codigo: "GENE00139", descripcion: "Pagos de Honorarios" },
  { codigo: "GENE00140", descripcion: "Ayuda Económica (externo)" },
  { codigo: "GENE00141", descripcion: "Pagos de Facturas" },
  { codigo: "GENE00142", descripcion: "Alquileres" },
  { codigo: "GENE00143", descripcion: "Movilidad (viáticos)" },
  { codigo: "GENE00144", descripcion: "Compras" },
  { codigo: "GENE00145", descripcion: "Certificados Inicio de Clases" },
  { codigo: "GENE00146", descripcion: "Certificado Finalización de Clases" },
  { codigo: "GENE00147", descripcion: "Asignaciones Familiares" },
  { codigo: "GENE00148", descripcion: "Rendición y Restitución de Fondo Fijo" },
  { codigo: "GENE00149", descripcion: "Honorarios Pasantes" },
  { codigo: "GENE00150", descripcion: "Renovación de Concesión" },
  { codigo: "GENE00151", descripcion: "Inhumación" },
  { codigo: "GENE00152", descripcion: "Exhumación" },
  { codigo: "GENE00153", descripcion: "Concesión" },
  { codigo: "GENE00154", descripcion: "Cambio de Titularidad" },
  { codigo: "GENE00155", descripcion: "Provisión de Combustibles" },
  { codigo: "GENE00156", descripcion: "Reparación Y Mantenimientos Insumos" },
  { codigo: "GENE00157", descripcion: "Oficio Judicial Interno" },
  { codigo: "GENE00158", descripcion: "Retiro Voluntario" },
  { codigo: "GENE00159", descripcion: "Devoluciones" },
  { codigo: "GENE00160", descripcion: "Alta y Baja de Seguros" },
  { codigo: "GENE00161", descripcion: "Extensión de Seguros" },
  { codigo: "GENE00162", descripcion: "Partes Mensuales de Asistencia de Personal Municipal" },
  { codigo: "GENE00163", descripcion: "Parte Médico de Largo Tratamiento" },
  { codigo: "GENE00164", descripcion: "Parte Médico de Accidentes Laborales" },
  { codigo: "GENE00165", descripcion: "Modificación de Indumentaria" },
  { codigo: "GENE00166", descripcion: "Licencia Anual Ordinaria" },
  { codigo: "GENE00167", descripcion: "Pago Horas Extraordinarias" },
  { codigo: "GENE00168", descripcion: "Pago Horas Extras" },
  { codigo: "GENE00169", descripcion: "Ley 5806 Licencia por tratamiento de hijo o cónyuge discapacitado" },
  { codigo: "GENE00170", descripcion: "Actualización de Precios de Contratos" },
  { codigo: "GENE00171", descripcion: "Contrato Locación de Servicios" },
  { codigo: "GENE00172", descripcion: "Certificación de Servicios Remuneraciones" },
  { codigo: "GENE00173", descripcion: "Renuncia Condicionada Docentes" },
  { codigo: "GENE00174", descripcion: "Renuncia por Jubilación" },
  { codigo: "GENE00175", descripcion: "Pasantía" },
  { codigo: "GENE00176", descripcion: "Caja Chica" },
  { codigo: "GENE00177", descripcion: "Mano de Obra" },
];

export const CODIGOS_EXPEDIENTES_SET = new Set(CODIGOS_EXPEDIENTES.map((item) => item.codigo));

export function codigoExpedienteLabel(codigo: string | null | undefined) {
  if (!codigo) return "-";
  const item = CODIGOS_EXPEDIENTES.find((entry) => entry.codigo === codigo);
  return item ? `${item.codigo} - ${item.descripcion}` : codigo;
}
