UPDATE "CatalogItem"
SET "active" = false,
    "updatedAt" = CURRENT_TIMESTAMP
WHERE "type" = 'expedient_category';

UPDATE "CatalogItem"
SET "module" = 'DESPACHO',
    "label" = CASE "value"
      WHEN 'AYUDA_ECONOMICA' THEN 'Ayuda economica'
      WHEN 'HONORARIOS' THEN 'Honorarios'
      WHEN 'CONTRATOS_DE_PERSONAL' THEN 'Contratos de personal'
      WHEN 'SOLICITUD_DE_INFORMES' THEN 'Solicitud de informes'
      WHEN 'INFORMES_NOVEDADES_SERENOS' THEN 'Informes / novedades de serenos'
      WHEN 'SOLICITUD_DE_INDUMENTARIA' THEN 'Solicitud de indumentaria'
      WHEN 'SOLICITUD_DE_CAMARAS' THEN 'Solicitud de camaras'
      WHEN 'SOLICITUD_DE_ELEMENTOS_DE_TRANSITO' THEN 'Solicitud de elementos de transito'
      WHEN 'PEDIDO_DE_ALFALFA_PARA_EQUINOS' THEN 'Pedido de alfalfa para equinos'
      WHEN 'PAGO_DE_FACTURA' THEN 'Pago de factura'
      WHEN 'PEDIDO_DE_PAGO_DE_FACTURA' THEN 'Pedido de pago de factura'
      WHEN 'REINTEGROS' THEN 'Reintegros'
      WHEN 'ALQUILERES' THEN 'Alquileres'
      WHEN 'INSUMOS_DE_LIBRERIA' THEN 'Insumos de libreria'
      WHEN 'ELEMENTOS_DE_LIMPIEZA' THEN 'Elementos de limpieza'
      WHEN 'ELEMENTOS_PARA_REACONDICIONAMIENTO' THEN 'Elementos para reacondicionamiento'
      WHEN 'VETERINARIA' THEN 'Veterinaria'
      WHEN 'MECANICA_MANTENIMIENTO_VEHICULAR' THEN 'Mecanica / mantenimiento vehicular'
      WHEN 'SERVICE_DE_CAMIONETA' THEN 'Service de camioneta'
      WHEN 'REPUESTOS_VEHICULARES' THEN 'Repuestos vehiculares'
      WHEN 'REPUESTOS_PARA_BICICLETAS' THEN 'Repuestos para bicicletas'
      WHEN 'MANTENIMIENTO_DE_MATAFUEGOS' THEN 'Mantenimiento de matafuegos'
      WHEN 'SOPORTE_TECNICO_INFORMATICA' THEN 'Soporte tecnico / informatica'
      WHEN 'BONIFICACION' THEN 'Bonificacion'
      WHEN 'ASISTENCIA_MENSUAL' THEN 'Asistencia mensual'
      WHEN 'VACACIONES' THEN 'Vacaciones'
      WHEN 'GESTION_DE_SEGUROS' THEN 'Gestion de seguros'
      WHEN 'LICENCIA_MEDICA' THEN 'Licencia medica'
      WHEN 'OTRO' THEN 'Otro'
    END,
    "active" = true,
    "sortOrder" = CASE "value"
      WHEN 'AYUDA_ECONOMICA' THEN 1
      WHEN 'HONORARIOS' THEN 2
      WHEN 'CONTRATOS_DE_PERSONAL' THEN 3
      WHEN 'SOLICITUD_DE_INFORMES' THEN 4
      WHEN 'INFORMES_NOVEDADES_SERENOS' THEN 5
      WHEN 'SOLICITUD_DE_INDUMENTARIA' THEN 6
      WHEN 'SOLICITUD_DE_CAMARAS' THEN 7
      WHEN 'SOLICITUD_DE_ELEMENTOS_DE_TRANSITO' THEN 8
      WHEN 'PEDIDO_DE_ALFALFA_PARA_EQUINOS' THEN 9
      WHEN 'PAGO_DE_FACTURA' THEN 10
      WHEN 'PEDIDO_DE_PAGO_DE_FACTURA' THEN 11
      WHEN 'REINTEGROS' THEN 12
      WHEN 'ALQUILERES' THEN 13
      WHEN 'INSUMOS_DE_LIBRERIA' THEN 14
      WHEN 'ELEMENTOS_DE_LIMPIEZA' THEN 15
      WHEN 'ELEMENTOS_PARA_REACONDICIONAMIENTO' THEN 16
      WHEN 'VETERINARIA' THEN 17
      WHEN 'MECANICA_MANTENIMIENTO_VEHICULAR' THEN 18
      WHEN 'SERVICE_DE_CAMIONETA' THEN 19
      WHEN 'REPUESTOS_VEHICULARES' THEN 20
      WHEN 'REPUESTOS_PARA_BICICLETAS' THEN 21
      WHEN 'MANTENIMIENTO_DE_MATAFUEGOS' THEN 22
      WHEN 'SOPORTE_TECNICO_INFORMATICA' THEN 23
      WHEN 'BONIFICACION' THEN 24
      WHEN 'ASISTENCIA_MENSUAL' THEN 25
      WHEN 'VACACIONES' THEN 26
      WHEN 'GESTION_DE_SEGUROS' THEN 27
      WHEN 'LICENCIA_MEDICA' THEN 28
      WHEN 'OTRO' THEN 29
    END,
    "updatedAt" = CURRENT_TIMESTAMP
WHERE "type" = 'expedient_category'
  AND "value" IN (
    'AYUDA_ECONOMICA',
    'HONORARIOS',
    'CONTRATOS_DE_PERSONAL',
    'SOLICITUD_DE_INFORMES',
    'INFORMES_NOVEDADES_SERENOS',
    'SOLICITUD_DE_INDUMENTARIA',
    'SOLICITUD_DE_CAMARAS',
    'SOLICITUD_DE_ELEMENTOS_DE_TRANSITO',
    'PEDIDO_DE_ALFALFA_PARA_EQUINOS',
    'PAGO_DE_FACTURA',
    'PEDIDO_DE_PAGO_DE_FACTURA',
    'REINTEGROS',
    'ALQUILERES',
    'INSUMOS_DE_LIBRERIA',
    'ELEMENTOS_DE_LIMPIEZA',
    'ELEMENTOS_PARA_REACONDICIONAMIENTO',
    'VETERINARIA',
    'MECANICA_MANTENIMIENTO_VEHICULAR',
    'SERVICE_DE_CAMIONETA',
    'REPUESTOS_VEHICULARES',
    'REPUESTOS_PARA_BICICLETAS',
    'MANTENIMIENTO_DE_MATAFUEGOS',
    'SOPORTE_TECNICO_INFORMATICA',
    'BONIFICACION',
    'ASISTENCIA_MENSUAL',
    'VACACIONES',
    'GESTION_DE_SEGUROS',
    'LICENCIA_MEDICA',
    'OTRO'
  );

INSERT INTO "CatalogItem" ("id", "type", "module", "value", "label", "active", "sortOrder", "createdAt", "updatedAt")
SELECT lower(hex(randomblob(16))), 'expedient_category', 'DESPACHO', source."value", source."label", true, source."sortOrder", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM (
  SELECT 'AYUDA_ECONOMICA' AS "value", 'Ayuda economica' AS "label", 1 AS "sortOrder"
  UNION ALL SELECT 'HONORARIOS', 'Honorarios', 2
  UNION ALL SELECT 'CONTRATOS_DE_PERSONAL', 'Contratos de personal', 3
  UNION ALL SELECT 'SOLICITUD_DE_INFORMES', 'Solicitud de informes', 4
  UNION ALL SELECT 'INFORMES_NOVEDADES_SERENOS', 'Informes / novedades de serenos', 5
  UNION ALL SELECT 'SOLICITUD_DE_INDUMENTARIA', 'Solicitud de indumentaria', 6
  UNION ALL SELECT 'SOLICITUD_DE_CAMARAS', 'Solicitud de camaras', 7
  UNION ALL SELECT 'SOLICITUD_DE_ELEMENTOS_DE_TRANSITO', 'Solicitud de elementos de transito', 8
  UNION ALL SELECT 'PEDIDO_DE_ALFALFA_PARA_EQUINOS', 'Pedido de alfalfa para equinos', 9
  UNION ALL SELECT 'PAGO_DE_FACTURA', 'Pago de factura', 10
  UNION ALL SELECT 'PEDIDO_DE_PAGO_DE_FACTURA', 'Pedido de pago de factura', 11
  UNION ALL SELECT 'REINTEGROS', 'Reintegros', 12
  UNION ALL SELECT 'ALQUILERES', 'Alquileres', 13
  UNION ALL SELECT 'INSUMOS_DE_LIBRERIA', 'Insumos de libreria', 14
  UNION ALL SELECT 'ELEMENTOS_DE_LIMPIEZA', 'Elementos de limpieza', 15
  UNION ALL SELECT 'ELEMENTOS_PARA_REACONDICIONAMIENTO', 'Elementos para reacondicionamiento', 16
  UNION ALL SELECT 'VETERINARIA', 'Veterinaria', 17
  UNION ALL SELECT 'MECANICA_MANTENIMIENTO_VEHICULAR', 'Mecanica / mantenimiento vehicular', 18
  UNION ALL SELECT 'SERVICE_DE_CAMIONETA', 'Service de camioneta', 19
  UNION ALL SELECT 'REPUESTOS_VEHICULARES', 'Repuestos vehiculares', 20
  UNION ALL SELECT 'REPUESTOS_PARA_BICICLETAS', 'Repuestos para bicicletas', 21
  UNION ALL SELECT 'MANTENIMIENTO_DE_MATAFUEGOS', 'Mantenimiento de matafuegos', 22
  UNION ALL SELECT 'SOPORTE_TECNICO_INFORMATICA', 'Soporte tecnico / informatica', 23
  UNION ALL SELECT 'BONIFICACION', 'Bonificacion', 24
  UNION ALL SELECT 'ASISTENCIA_MENSUAL', 'Asistencia mensual', 25
  UNION ALL SELECT 'VACACIONES', 'Vacaciones', 26
  UNION ALL SELECT 'GESTION_DE_SEGUROS', 'Gestion de seguros', 27
  UNION ALL SELECT 'LICENCIA_MEDICA', 'Licencia medica', 28
  UNION ALL SELECT 'OTRO', 'Otro', 29
) AS source
WHERE NOT EXISTS (
  SELECT 1
  FROM "CatalogItem" existing
  WHERE existing."type" = 'expedient_category'
    AND existing."value" = source."value"
);
